[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[project]
name = "dynamotable"
dynamic = ["version"]
description = "Read and write Dynamo table files as pandas dataframes"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "BSD-3-Clause" }
authors = [{ name = "Alister Burt", email = "alisterburt@gmail.com" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = ["IO", "dynamo", "table file", "cryo-EM", "cryo-ET"]
dependencies = ["pandas>=1.0.5"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[project.urls]
homepage = "https://github.com/alisterburt/dynamotable"
repository = "https://github.com/alisterburt/dynamotable"

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.coverage.run]
source = ["dynamotable"]
